import type { CompanyApplication } from "@/store/useApplicationStore";

export const companyApplications: CompanyApplication[] = [
  {
    id: "APP-001",
    company: "Tata Steel Ltd",
    cin: "L27100MH1907PLC000260",
    sector: "Steel & Metals",
    loanAmount: 500,
    riskScore: 28,
    riskCategory: "Low",
    status: "Approved",
    defaultProbability: 0.05,
    recommendation: "Approve",
    interestRate: "9.0%",
    suggestedLimit: "₹500 Cr",
    incorporationYear: "1907",
    registeredOffice: "Mumbai, Maharashtra",
    promoterGroup: "Tata Group",
    cibilScore: 742,
    financials: {
      revenue: "₹2,847 Cr",
      outstandingDebt: "₹1,205 Cr",
      dscr: 1.4,
      debtEquity: 0.8,
      relatedPartyTransactions: "₹145 Cr",
      gstMismatch: true,
      gstMismatchAmount: "₹23.5 Cr",
      interestCoverage: 3.2,
      currentRatio: 1.8,
    },
    fiveCsScores: [
      { name: "Character", score: 78, weight: 20, contribution: 15.6, explanation: "Strong promoter track record with 25+ years. Clean CIBIL history." },
      { name: "Capacity", score: 65, weight: 25, contribution: 16.25, explanation: "DSCR at 1.4x — adequate but below ideal 1.5x threshold." },
      { name: "Capital", score: 82, weight: 20, contribution: 16.4, explanation: "Debt-to-Equity at 0.8x. Strong net worth of ₹450 Cr." },
      { name: "Collateral", score: 55, weight: 15, contribution: 8.25, explanation: "Primary security covers 1.2x of loan. Valuation needs reassessment." },
      { name: "Conditions", score: 48, weight: 20, contribution: 9.6, explanation: "Steel sector facing headwinds. Raw material cost volatility." },
    ],
    documents: [
      { id: "1", name: "Certificate_of_Incorporation.pdf", type: "Certificate of Incorporation", size: "2.4 MB", status: "verified" },
      { id: "2", name: "Company_PAN.pdf", type: "Company PAN", size: "1.1 MB", status: "verified" },
      { id: "3", name: "GST_Registration.pdf", type: "GST Registration", size: "890 KB", status: "verified" },
      { id: "4", name: "MOA_TataSteel.pdf", type: "Memorandum of Association", size: "5.2 MB", status: "pending" },
      { id: "5", name: "Director_KYC_Bundle.zip", type: "Director KYC", size: "8.1 MB", status: "failed" },
    ],
    validations: [
      { check: "PAN vs GSTIN Match", status: "pass", detail: "PAN AAACT2727Q matches GSTIN prefix" },
      { check: "CIN Format Valid", status: "pass", detail: "L27100MH1907PLC000260 — valid format" },
      { check: "Company Name Consistency", status: "pass", detail: "Matches across all documents" },
      { check: "Director Identity Match", status: "warning", detail: "1 director name has slight variation" },
      { check: "Director DIN Verification", status: "fail", detail: "1 director DIN not found in MCA records" },
    ],
    integrityScore: 87,
    researchFindings: [
      { source: "Economic Times", date: "2026-02-28", title: "Steel sector braces for margin squeeze", sentiment: "Negative", confidence: 87 },
      { source: "CRISIL Report", date: "2026-02-25", title: "Credit outlook stable for large steel manufacturers", sentiment: "Neutral", confidence: 92 },
      { source: "MCA Filing", date: "2026-02-20", title: "Annual return filed — No adverse remarks", sentiment: "Positive", confidence: 95 },
    ],
    explainableAI: [
      { severity: "high", text: "High litigation exposure — 2 pending cases worth ₹12 Cr in e-Courts data." },
      { severity: "medium", text: "Revenue mismatch — GSTR-2A vs 3B discrepancy of ₹23.5 Cr." },
      { severity: "low", text: "Strong promoter track record — 25+ years, clean CIBIL history." },
    ],
    pipeline: [
      { stage: "Draft", status: "completed", date: "Feb 15, 2026" },
      { stage: "Data Ingestion", status: "completed", date: "Feb 18, 2026" },
      { stage: "AI Research", status: "completed", date: "Feb 20, 2026" },
      { stage: "Risk Scoring", status: "completed", date: "Feb 22, 2026" },
      { stage: "Committee Review", status: "active", date: "In Progress" },
      { stage: "Final Decision", status: "pending", date: "—" },
    ],
    comments: [
      { author: "Rajesh Kumar", role: "Credit Manager", time: "2 hours ago", text: "GST mismatch flagged. Requesting clarification from CA firm." },
      { author: "Priya Sharma", role: "Risk Analyst", time: "5 hours ago", text: "Collateral valuation report is 6 months old." },
    ],
  },
  {
    id: "APP-002",
    company: "Reliance Industries",
    cin: "L17110MH1973PLC019786",
    sector: "Petrochemicals",
    loanAmount: 1200,
    riskScore: 35,
    riskCategory: "Medium",
    status: "Under Review",
    defaultProbability: 0.18,
    recommendation: "Conditional Approval",
    interestRate: "10.25%",
    suggestedLimit: "₹1,000 Cr",
    incorporationYear: "1973",
    registeredOffice: "Mumbai, Maharashtra",
    promoterGroup: "Ambani Group",
    cibilScore: 780,
    financials: {
      revenue: "₹8,500 Cr",
      outstandingDebt: "₹3,200 Cr",
      dscr: 2.1,
      debtEquity: 0.5,
      relatedPartyTransactions: "₹580 Cr",
      gstMismatch: false,
      gstMismatchAmount: "",
      interestCoverage: 5.4,
      currentRatio: 2.3,
    },
    fiveCsScores: [
      { name: "Character", score: 90, weight: 20, contribution: 18.0, explanation: "Established conglomerate with decades of credit history." },
      { name: "Capacity", score: 85, weight: 25, contribution: 21.25, explanation: "Strong DSCR at 2.1x. Robust cash flow generation." },
      { name: "Capital", score: 88, weight: 20, contribution: 17.6, explanation: "Low leverage at 0.5x D/E. Massive net worth." },
      { name: "Collateral", score: 70, weight: 15, contribution: 10.5, explanation: "Adequate security with refinery assets as collateral." },
      { name: "Conditions", score: 60, weight: 20, contribution: 12.0, explanation: "Oil price volatility and regulatory changes in energy sector." },
    ],
    documents: [
      { id: "1", name: "Certificate_of_Incorporation_RIL.pdf", type: "Certificate of Incorporation", size: "3.1 MB", status: "verified" },
      { id: "2", name: "RIL_PAN.pdf", type: "Company PAN", size: "950 KB", status: "verified" },
      { id: "3", name: "GST_Registration_RIL.pdf", type: "GST Registration", size: "1.2 MB", status: "verified" },
      { id: "4", name: "Director_KYC_RIL.zip", type: "Director KYC", size: "12 MB", status: "verified" },
    ],
    validations: [
      { check: "PAN vs GSTIN Match", status: "pass", detail: "PAN matches GSTIN prefix" },
      { check: "CIN Format Valid", status: "pass", detail: "Valid CIN format confirmed" },
      { check: "Company Name Consistency", status: "pass", detail: "Consistent across all documents" },
      { check: "Director Identity Match", status: "pass", detail: "All directors verified" },
    ],
    integrityScore: 95,
    researchFindings: [
      { source: "Bloomberg", date: "2026-03-01", title: "Reliance Jio revenue up 18% YoY", sentiment: "Positive", confidence: 94 },
      { source: "Reuters", date: "2026-02-27", title: "Global oil prices remain volatile", sentiment: "Negative", confidence: 85 },
      { source: "CRISIL", date: "2026-02-22", title: "AAA rating reaffirmed for Reliance", sentiment: "Positive", confidence: 97 },
    ],
    explainableAI: [
      { severity: "low", text: "Excellent credit history with zero defaults across all facilities." },
      { severity: "medium", text: "High related party transactions at ₹580 Cr need monitoring." },
      { severity: "low", text: "Strong diversification across energy, telecom, and retail verticals." },
    ],
    pipeline: [
      { stage: "Draft", status: "completed", date: "Mar 1, 2026" },
      { stage: "Data Ingestion", status: "completed", date: "Mar 3, 2026" },
      { stage: "AI Research", status: "completed", date: "Mar 4, 2026" },
      { stage: "Risk Scoring", status: "active", date: "In Progress" },
      { stage: "Committee Review", status: "pending", date: "—" },
      { stage: "Final Decision", status: "pending", date: "—" },
    ],
    comments: [
      { author: "Amit Desai", role: "Senior Manager", time: "1 hour ago", text: "Large exposure — needs board-level approval for limits above ₹1000 Cr." },
    ],
  },
  {
    id: "APP-003",
    company: "Adani Ports & SEZ",
    cin: "L63090GJ1998PLC034182",
    sector: "Infrastructure",
    loanAmount: 800,
    riskScore: 72,
    riskCategory: "High",
    status: "High Risk",
    defaultProbability: 0.42,
    recommendation: "Review",
    interestRate: "12.5%",
    suggestedLimit: "₹500 Cr",
    incorporationYear: "1998",
    registeredOffice: "Ahmedabad, Gujarat",
    promoterGroup: "Adani Group",
    cibilScore: 680,
    financials: {
      revenue: "₹4,200 Cr",
      outstandingDebt: "₹6,100 Cr",
      dscr: 0.9,
      debtEquity: 2.8,
      relatedPartyTransactions: "₹920 Cr",
      gstMismatch: true,
      gstMismatchAmount: "₹45 Cr",
      interestCoverage: 1.1,
      currentRatio: 0.7,
    },
    fiveCsScores: [
      { name: "Character", score: 55, weight: 20, contribution: 11.0, explanation: "Governance concerns raised by international investors." },
      { name: "Capacity", score: 35, weight: 25, contribution: 8.75, explanation: "DSCR below 1.0x — significant debt servicing risk." },
      { name: "Capital", score: 30, weight: 20, contribution: 6.0, explanation: "High leverage at 2.8x D/E. Negative working capital." },
      { name: "Collateral", score: 60, weight: 15, contribution: 9.0, explanation: "Port assets provide decent collateral cover." },
      { name: "Conditions", score: 40, weight: 20, contribution: 8.0, explanation: "Infrastructure sector outlook mixed. Regulatory approvals pending." },
    ],
    documents: [
      { id: "1", name: "COI_AdaniPorts.pdf", type: "Certificate of Incorporation", size: "2.8 MB", status: "verified" },
      { id: "2", name: "PAN_Adani.pdf", type: "Company PAN", size: "1.0 MB", status: "verified" },
      { id: "3", name: "GST_Adani.pdf", type: "GST Registration", size: "1.1 MB", status: "failed" },
      { id: "4", name: "MOA_Adani.pdf", type: "Memorandum of Association", size: "4.5 MB", status: "pending" },
      { id: "5", name: "Director_KYC_Adani.zip", type: "Director KYC", size: "9.5 MB", status: "pending" },
    ],
    validations: [
      { check: "PAN vs GSTIN Match", status: "pass", detail: "PAN matches GSTIN prefix" },
      { check: "CIN Format Valid", status: "pass", detail: "Valid CIN confirmed" },
      { check: "Company Name Consistency", status: "warning", detail: "Minor variation in subsidiary naming" },
      { check: "GST Registration Active", status: "fail", detail: "GST registration shows discrepancy" },
      { check: "Director DIN Verification", status: "warning", detail: "2 directors have multiple directorships flagged" },
    ],
    integrityScore: 62,
    researchFindings: [
      { source: "Hindenburg Report", date: "2026-01-15", title: "Governance and accounting concerns raised", sentiment: "Negative", confidence: 78 },
      { source: "CRISIL", date: "2026-02-10", title: "Rating under watch for downgrade", sentiment: "Negative", confidence: 88 },
      { source: "MCA Filing", date: "2026-02-20", title: "Related party transaction disclosures flagged", sentiment: "Negative", confidence: 82 },
    ],
    explainableAI: [
      { severity: "high", text: "Critical debt-to-equity ratio at 2.8x — significantly above sector average of 1.2x." },
      { severity: "high", text: "DSCR below 1.0x indicates inability to service existing debt from operations." },
      { severity: "high", text: "Governance concerns flagged by multiple international research firms." },
      { severity: "medium", text: "GST registration discrepancy of ₹45 Cr needs immediate resolution." },
    ],
    pipeline: [
      { stage: "Draft", status: "completed", date: "Jan 20, 2026" },
      { stage: "Data Ingestion", status: "completed", date: "Jan 25, 2026" },
      { stage: "AI Research", status: "completed", date: "Feb 1, 2026" },
      { stage: "Risk Scoring", status: "completed", date: "Feb 5, 2026" },
      { stage: "Committee Review", status: "active", date: "In Progress" },
      { stage: "Final Decision", status: "pending", date: "—" },
    ],
    comments: [
      { author: "Priya Sharma", role: "Risk Analyst", time: "30 min ago", text: "Strongly recommend additional due diligence before proceeding." },
      { author: "Amit Desai", role: "Senior Manager", time: "3 hours ago", text: "Escalated to risk committee for review." },
    ],
  },
  {
    id: "APP-004",
    company: "Infosys Ltd",
    cin: "L85110KA1981PLC013115",
    sector: "IT Services",
    loanAmount: 350,
    riskScore: 18,
    riskCategory: "Low",
    status: "Approved",
    defaultProbability: 0.02,
    recommendation: "Approve",
    interestRate: "8.5%",
    suggestedLimit: "₹350 Cr",
    incorporationYear: "1981",
    registeredOffice: "Bangalore, Karnataka",
    promoterGroup: "Infosys Founders",
    cibilScore: 820,
    financials: {
      revenue: "₹15,400 Cr",
      outstandingDebt: "₹850 Cr",
      dscr: 4.2,
      debtEquity: 0.15,
      relatedPartyTransactions: "₹120 Cr",
      gstMismatch: false,
      gstMismatchAmount: "",
      interestCoverage: 12.5,
      currentRatio: 3.4,
    },
    fiveCsScores: [
      { name: "Character", score: 95, weight: 20, contribution: 19.0, explanation: "Gold-standard corporate governance. Zero defaults ever." },
      { name: "Capacity", score: 92, weight: 25, contribution: 23.0, explanation: "Exceptional DSCR at 4.2x. Strong recurring revenue model." },
      { name: "Capital", score: 96, weight: 20, contribution: 19.2, explanation: "Minimal leverage at 0.15x D/E. Cash-rich balance sheet." },
      { name: "Collateral", score: 85, weight: 15, contribution: 12.75, explanation: "Strong brand value and IP portfolio as soft collateral." },
      { name: "Conditions", score: 80, weight: 20, contribution: 16.0, explanation: "IT services sector remains resilient. Digital transformation demand strong." },
    ],
    documents: [
      { id: "1", name: "COI_Infosys.pdf", type: "Certificate of Incorporation", size: "2.2 MB", status: "verified" },
      { id: "2", name: "PAN_Infosys.pdf", type: "Company PAN", size: "800 KB", status: "verified" },
      { id: "3", name: "GST_Infosys.pdf", type: "GST Registration", size: "1.0 MB", status: "verified" },
      { id: "4", name: "Director_KYC_Infosys.zip", type: "Director KYC", size: "6.5 MB", status: "verified" },
    ],
    validations: [
      { check: "PAN vs GSTIN Match", status: "pass", detail: "Perfect match confirmed" },
      { check: "CIN Format Valid", status: "pass", detail: "Valid CIN format" },
      { check: "Company Name Consistency", status: "pass", detail: "Consistent across all documents" },
      { check: "Director Identity Match", status: "pass", detail: "All directors verified via DIN" },
      { check: "GST Registration Active", status: "pass", detail: "Active registration confirmed" },
    ],
    integrityScore: 98,
    researchFindings: [
      { source: "Gartner", date: "2026-03-02", title: "Infosys named leader in IT services Magic Quadrant", sentiment: "Positive", confidence: 96 },
      { source: "Bloomberg", date: "2026-02-28", title: "Record deal wins in Q3 FY26", sentiment: "Positive", confidence: 93 },
      { source: "MCA Filing", date: "2026-02-15", title: "Clean audit report — no qualifications", sentiment: "Positive", confidence: 98 },
    ],
    explainableAI: [
      { severity: "low", text: "Exemplary financial health across all metrics. Top-tier credit profile." },
      { severity: "low", text: "Minimal debt and exceptional cash flow generation from operations." },
      { severity: "low", text: "IT services sector showing continued resilience and growth." },
    ],
    pipeline: [
      { stage: "Draft", status: "completed", date: "Feb 25, 2026" },
      { stage: "Data Ingestion", status: "completed", date: "Feb 27, 2026" },
      { stage: "AI Research", status: "completed", date: "Mar 1, 2026" },
      { stage: "Risk Scoring", status: "completed", date: "Mar 2, 2026" },
      { stage: "Committee Review", status: "completed", date: "Mar 4, 2026" },
      { stage: "Final Decision", status: "completed", date: "Mar 5, 2026" },
    ],
    comments: [
      { author: "Rajesh Kumar", role: "Credit Manager", time: "1 day ago", text: "Fast-tracked due to excellent credit profile." },
    ],
  },
  {
    id: "APP-005",
    company: "Bajaj Finance",
    cin: "L65910MH1987PLC042961",
    sector: "NBFC",
    loanAmount: 600,
    riskScore: 45,
    riskCategory: "Medium",
    status: "Under Review",
    defaultProbability: 0.22,
    recommendation: "Conditional Approval",
    interestRate: "10.5%",
    suggestedLimit: "₹450 Cr",
    incorporationYear: "1987",
    registeredOffice: "Pune, Maharashtra",
    promoterGroup: "Bajaj Group",
    cibilScore: 755,
    financials: {
      revenue: "₹6,200 Cr",
      outstandingDebt: "₹4,800 Cr",
      dscr: 1.6,
      debtEquity: 1.4,
      relatedPartyTransactions: "₹340 Cr",
      gstMismatch: false,
      gstMismatchAmount: "",
      interestCoverage: 2.8,
      currentRatio: 1.3,
    },
    fiveCsScores: [
      { name: "Character", score: 80, weight: 20, contribution: 16.0, explanation: "Well-established NBFC with strong management team." },
      { name: "Capacity", score: 68, weight: 25, contribution: 17.0, explanation: "DSCR at 1.6x — adequate. NPA ratio rising slightly." },
      { name: "Capital", score: 60, weight: 20, contribution: 12.0, explanation: "D/E at 1.4x — normal for NBFC but needs monitoring." },
      { name: "Collateral", score: 50, weight: 15, contribution: 7.5, explanation: "Loan book as collateral. Asset quality under watch." },
      { name: "Conditions", score: 55, weight: 20, contribution: 11.0, explanation: "NBFC sector under RBI scrutiny. Tightening norms." },
    ],
    documents: [
      { id: "1", name: "COI_BajajFinance.pdf", type: "Certificate of Incorporation", size: "2.6 MB", status: "verified" },
      { id: "2", name: "PAN_Bajaj.pdf", type: "Company PAN", size: "920 KB", status: "verified" },
      { id: "3", name: "GST_Bajaj.pdf", type: "GST Registration", size: "1.1 MB", status: "verified" },
      { id: "4", name: "RBI_License_Bajaj.pdf", type: "RBI NBFC License", size: "3.2 MB", status: "verified" },
      { id: "5", name: "Director_KYC_Bajaj.zip", type: "Director KYC", size: "7.8 MB", status: "pending" },
    ],
    validations: [
      { check: "PAN vs GSTIN Match", status: "pass", detail: "PAN matches GSTIN prefix" },
      { check: "CIN Format Valid", status: "pass", detail: "Valid CIN format" },
      { check: "RBI License Valid", status: "pass", detail: "Active NBFC-ND-SI license confirmed" },
      { check: "Director Identity Match", status: "warning", detail: "1 director KYC pending verification" },
    ],
    integrityScore: 88,
    researchFindings: [
      { source: "RBI Bulletin", date: "2026-03-01", title: "Tighter norms for NBFC lending proposed", sentiment: "Negative", confidence: 90 },
      { source: "CRISIL", date: "2026-02-25", title: "Bajaj Finance maintains AA+ rating", sentiment: "Positive", confidence: 95 },
      { source: "Economic Times", date: "2026-02-20", title: "Consumer lending growth slowing in Q4", sentiment: "Negative", confidence: 82 },
    ],
    explainableAI: [
      { severity: "medium", text: "NBFC sector facing tightening regulatory environment from RBI." },
      { severity: "medium", text: "Rising NPA ratio from 1.2% to 1.8% in last two quarters." },
      { severity: "low", text: "Strong brand and market position in consumer lending segment." },
    ],
    pipeline: [
      { stage: "Draft", status: "completed", date: "Feb 20, 2026" },
      { stage: "Data Ingestion", status: "completed", date: "Feb 23, 2026" },
      { stage: "AI Research", status: "completed", date: "Feb 26, 2026" },
      { stage: "Risk Scoring", status: "completed", date: "Feb 28, 2026" },
      { stage: "Committee Review", status: "active", date: "In Progress" },
      { stage: "Final Decision", status: "pending", date: "—" },
    ],
    comments: [
      { author: "Priya Sharma", role: "Risk Analyst", time: "4 hours ago", text: "NPA trend needs close watch. Recommend quarterly review clause." },
    ],
  },
  {
    id: "APP-006",
    company: "JSW Steel Ltd",
    cin: "L27102MH1994PLC152925",
    sector: "Steel & Metals",
    loanAmount: 450,
    riskScore: 58,
    riskCategory: "Medium",
    status: "Pending",
    defaultProbability: 0.28,
    recommendation: "Conditional Approval",
    interestRate: "11.0%",
    suggestedLimit: "₹350 Cr",
    incorporationYear: "1994",
    registeredOffice: "Mumbai, Maharashtra",
    promoterGroup: "Jindal Group",
    cibilScore: 710,
    financials: {
      revenue: "₹3,800 Cr",
      outstandingDebt: "₹2,900 Cr",
      dscr: 1.2,
      debtEquity: 1.6,
      relatedPartyTransactions: "₹280 Cr",
      gstMismatch: true,
      gstMismatchAmount: "₹18 Cr",
      interestCoverage: 1.8,
      currentRatio: 1.1,
    },
    fiveCsScores: [
      { name: "Character", score: 70, weight: 20, contribution: 14.0, explanation: "Experienced promoter with mixed track record across group companies." },
      { name: "Capacity", score: 50, weight: 25, contribution: 12.5, explanation: "DSCR at 1.2x — marginal. Capacity utilization below industry average." },
      { name: "Capital", score: 45, weight: 20, contribution: 9.0, explanation: "D/E at 1.6x — elevated. Working capital cycle stretched." },
      { name: "Collateral", score: 65, weight: 15, contribution: 9.75, explanation: "Plant and machinery as primary security. Adequate coverage." },
      { name: "Conditions", score: 48, weight: 20, contribution: 9.6, explanation: "Steel sector facing margin pressure. Export demand softening." },
    ],
    documents: [
      { id: "1", name: "COI_JSW.pdf", type: "Certificate of Incorporation", size: "2.5 MB", status: "verified" },
      { id: "2", name: "PAN_JSW.pdf", type: "Company PAN", size: "850 KB", status: "verified" },
      { id: "3", name: "GST_JSW.pdf", type: "GST Registration", size: "1.0 MB", status: "pending" },
      { id: "4", name: "Financial_Statements_JSW.pdf", type: "Financial Statements", size: "15 MB", status: "verified" },
      { id: "5", name: "Director_KYC_JSW.zip", type: "Director KYC", size: "8.5 MB", status: "verified" },
    ],
    validations: [
      { check: "PAN vs GSTIN Match", status: "pass", detail: "PAN matches GSTIN prefix" },
      { check: "CIN Format Valid", status: "pass", detail: "Valid CIN format" },
      { check: "GST Registration Active", status: "warning", detail: "GST mismatch of ₹18 Cr flagged" },
      { check: "Director Identity Match", status: "pass", detail: "All directors verified" },
    ],
    integrityScore: 78,
    researchFindings: [
      { source: "Economic Times", date: "2026-02-28", title: "JSW Steel reports margin decline in Q3", sentiment: "Negative", confidence: 85 },
      { source: "ICRA", date: "2026-02-20", title: "Rating maintained at A+ with stable outlook", sentiment: "Neutral", confidence: 90 },
    ],
    explainableAI: [
      { severity: "medium", text: "DSCR at 1.2x is marginal — any revenue decline could trigger stress." },
      { severity: "medium", text: "GST mismatch of ₹18 Cr requires resolution before disbursement." },
      { severity: "high", text: "Capacity utilization at 55% — significantly below breakeven threshold." },
    ],
    pipeline: [
      { stage: "Draft", status: "completed", date: "Feb 10, 2026" },
      { stage: "Data Ingestion", status: "completed", date: "Feb 14, 2026" },
      { stage: "AI Research", status: "completed", date: "Feb 18, 2026" },
      { stage: "Risk Scoring", status: "active", date: "In Progress" },
      { stage: "Committee Review", status: "pending", date: "—" },
      { stage: "Final Decision", status: "pending", date: "—" },
    ],
    comments: [
      { author: "Rajesh Kumar", role: "Credit Manager", time: "6 hours ago", text: "Need updated capacity utilization data before final scoring." },
    ],
  },
  {
    id: "APP-007",
    company: "HDFC Ltd",
    cin: "L70100MH1977PLC019916",
    sector: "Housing Finance",
    loanAmount: 900,
    riskScore: 22,
    riskCategory: "Low",
    status: "Approved",
    defaultProbability: 0.03,
    recommendation: "Approve",
    interestRate: "8.75%",
    suggestedLimit: "₹900 Cr",
    incorporationYear: "1977",
    registeredOffice: "Mumbai, Maharashtra",
    promoterGroup: "HDFC Group",
    cibilScore: 810,
    financials: {
      revenue: "₹12,000 Cr",
      outstandingDebt: "₹5,500 Cr",
      dscr: 3.5,
      debtEquity: 0.6,
      relatedPartyTransactions: "₹200 Cr",
      gstMismatch: false,
      gstMismatchAmount: "",
      interestCoverage: 8.2,
      currentRatio: 2.8,
    },
    fiveCsScores: [
      { name: "Character", score: 92, weight: 20, contribution: 18.4, explanation: "Institutional quality management. Pristine track record." },
      { name: "Capacity", score: 88, weight: 25, contribution: 22.0, explanation: "Exceptional DSCR at 3.5x. Stable revenue growth." },
      { name: "Capital", score: 90, weight: 20, contribution: 18.0, explanation: "Conservative leverage at 0.6x D/E." },
      { name: "Collateral", score: 82, weight: 15, contribution: 12.3, explanation: "Housing loan portfolio provides excellent collateral." },
      { name: "Conditions", score: 78, weight: 20, contribution: 15.6, explanation: "Housing finance sector benefiting from govt push." },
    ],
    documents: [
      { id: "1", name: "COI_HDFC.pdf", type: "Certificate of Incorporation", size: "2.3 MB", status: "verified" },
      { id: "2", name: "PAN_HDFC.pdf", type: "Company PAN", size: "900 KB", status: "verified" },
      { id: "3", name: "GST_HDFC.pdf", type: "GST Registration", size: "1.0 MB", status: "verified" },
      { id: "4", name: "Director_KYC_HDFC.zip", type: "Director KYC", size: "7.0 MB", status: "verified" },
    ],
    validations: [
      { check: "PAN vs GSTIN Match", status: "pass", detail: "Perfect match" },
      { check: "CIN Format Valid", status: "pass", detail: "Valid CIN" },
      { check: "Company Name Consistency", status: "pass", detail: "Consistent" },
      { check: "Director Identity Match", status: "pass", detail: "All verified" },
    ],
    integrityScore: 97,
    researchFindings: [
      { source: "RBI", date: "2026-03-01", title: "Housing finance growth at 15% YoY", sentiment: "Positive", confidence: 95 },
      { source: "CRISIL", date: "2026-02-25", title: "AAA rating reaffirmed", sentiment: "Positive", confidence: 98 },
    ],
    explainableAI: [
      { severity: "low", text: "Top-tier credit profile with exceptional financial health indicators." },
      { severity: "low", text: "Housing sector tailwinds from government affordable housing scheme." },
    ],
    pipeline: [
      { stage: "Draft", status: "completed", date: "Feb 28, 2026" },
      { stage: "Data Ingestion", status: "completed", date: "Mar 1, 2026" },
      { stage: "AI Research", status: "completed", date: "Mar 2, 2026" },
      { stage: "Risk Scoring", status: "completed", date: "Mar 3, 2026" },
      { stage: "Committee Review", status: "completed", date: "Mar 5, 2026" },
      { stage: "Final Decision", status: "completed", date: "Mar 6, 2026" },
    ],
    comments: [
      { author: "Amit Desai", role: "Senior Manager", time: "2 days ago", text: "Approved. Standard terms apply." },
    ],
  },
  {
    id: "APP-008",
    company: "Vedanta Ltd",
    cin: "L13209MH1965PLC291394",
    sector: "Mining",
    loanAmount: 700,
    riskScore: 81,
    riskCategory: "High",
    status: "Rejected",
    defaultProbability: 0.55,
    recommendation: "Reject",
    interestRate: "N/A",
    suggestedLimit: "N/A",
    incorporationYear: "1965",
    registeredOffice: "Mumbai, Maharashtra",
    promoterGroup: "Vedanta Resources",
    cibilScore: 620,
    financials: {
      revenue: "₹5,100 Cr",
      outstandingDebt: "₹7,800 Cr",
      dscr: 0.6,
      debtEquity: 3.5,
      relatedPartyTransactions: "₹1,200 Cr",
      gstMismatch: true,
      gstMismatchAmount: "₹62 Cr",
      interestCoverage: 0.8,
      currentRatio: 0.5,
    },
    fiveCsScores: [
      { name: "Character", score: 40, weight: 20, contribution: 8.0, explanation: "Multiple governance issues. Promoter pledge at 85%." },
      { name: "Capacity", score: 25, weight: 25, contribution: 6.25, explanation: "DSCR at 0.6x — unable to service debt from cash flows." },
      { name: "Capital", score: 20, weight: 20, contribution: 4.0, explanation: "Extreme leverage at 3.5x D/E. Negative net worth risk." },
      { name: "Collateral", score: 45, weight: 15, contribution: 6.75, explanation: "Mining assets with environmental liability concerns." },
      { name: "Conditions", score: 30, weight: 20, contribution: 6.0, explanation: "Mining sector facing environmental regulatory tightening." },
    ],
    documents: [
      { id: "1", name: "COI_Vedanta.pdf", type: "Certificate of Incorporation", size: "2.7 MB", status: "verified" },
      { id: "2", name: "PAN_Vedanta.pdf", type: "Company PAN", size: "950 KB", status: "verified" },
      { id: "3", name: "GST_Vedanta.pdf", type: "GST Registration", size: "1.2 MB", status: "failed" },
      { id: "4", name: "Environmental_Clearance.pdf", type: "Environmental Clearance", size: "4.0 MB", status: "failed" },
      { id: "5", name: "Director_KYC_Vedanta.zip", type: "Director KYC", size: "10 MB", status: "pending" },
    ],
    validations: [
      { check: "PAN vs GSTIN Match", status: "pass", detail: "PAN matches" },
      { check: "CIN Format Valid", status: "pass", detail: "Valid CIN" },
      { check: "Environmental Clearance", status: "fail", detail: "Expired clearance for 2 mining sites" },
      { check: "GST Registration Active", status: "fail", detail: "GST discrepancy of ₹62 Cr flagged" },
      { check: "Director DIN Verification", status: "fail", detail: "2 directors flagged for shell company links" },
    ],
    integrityScore: 45,
    researchFindings: [
      { source: "e-Courts", date: "2026-02-15", title: "5 active litigation cases including environmental", sentiment: "Negative", confidence: 90 },
      { source: "NGT Order", date: "2026-02-10", title: "Mining operations partially suspended", sentiment: "Negative", confidence: 95 },
      { source: "CRISIL", date: "2026-02-01", title: "Rating downgraded to BBB-", sentiment: "Negative", confidence: 92 },
    ],
    explainableAI: [
      { severity: "high", text: "Extreme leverage at 3.5x D/E with DSCR below 1.0x — critical default risk." },
      { severity: "high", text: "Environmental clearance expired — operations partially suspended by NGT." },
      { severity: "high", text: "Promoter pledge at 85% — any stock price decline triggers margin calls." },
      { severity: "high", text: "GST discrepancy of ₹62 Cr and multiple director red flags." },
    ],
    pipeline: [
      { stage: "Draft", status: "completed", date: "Jan 10, 2026" },
      { stage: "Data Ingestion", status: "completed", date: "Jan 15, 2026" },
      { stage: "AI Research", status: "completed", date: "Jan 20, 2026" },
      { stage: "Risk Scoring", status: "completed", date: "Jan 25, 2026" },
      { stage: "Committee Review", status: "completed", date: "Feb 1, 2026" },
      { stage: "Final Decision", status: "completed", date: "Feb 3, 2026" },
    ],
    comments: [
      { author: "Amit Desai", role: "Senior Manager", time: "1 month ago", text: "Rejected. Too many red flags across all parameters." },
      { author: "Priya Sharma", role: "Risk Analyst", time: "1 month ago", text: "Environmental and governance risks are deal-breakers." },
    ],
  },
];
